# Parameters for your particle filter

#using
motion_params:
  vel_std:    0.02
  delta_std:  0.1
  x_std:      0.01
  y_std:      0.01
  theta_std:  0.01

# sensor_params:
#   hit_std:    2.5
#   z_hit:      0.8
#   z_short:    0.05
#   z_max:      0.05
#   z_rand:     0.8


# motion_params:
#   vel_std:    0.00
#   delta_std:  0.1
#   x_std:      0.01
#   y_std:      0.01
#   theta_std:  0.01

#using
# sensor_params:
#   hit_std:    2.2
#   z_hit:      0.6
#   z_short:    0.155
#   z_max:      0.05
#   z_rand:     0.8

sensor_params:
  hit_std:    2.2
  z_hit:      0.6
  z_short:    0.155
  z_max:      0.05
  z_rand:     0.8